# Adds ports to the db and access to the temporal UI for debugging purposes.
# Expected to be used like this:
# VERSION=dev docker-compose -f docker-compose.yaml -f docker-compose.debug.yaml up
version: "3.7"
x-logging: &default-logging
  options:
    max-size: "100m"
    max-file: "5"
  driver: json-file
services:
  db:
    ports:
      - "8011:1099"
  airbyte-temporal-ui:
    image: temporalio/web:1.13.0
    logging: *default-logging
    container_name: airbyte-temporal-ui
    restart: unless-stopped
    environment:
      - TEMPORAL_GRPC_ENDPOINT=airbyte-temporal:7233
      - TEMPORAL_PERMIT_WRITE_API=true
    ports:
      - "8012:8088"
  # IMPORTANT: the internal and external ports for JMX must be the same!
  # see https://forums.docker.com/t/exposing-mapped-jmx-ports-from-multiple-containers/5287/6 for more info
  server:
    ports:
      - "8014:8014"
  scheduler:
    ports:
      - "8015:8015"
  worker:
    ports:
      - "8016:8016"
