apiVersion: v1
kind: Pod
metadata:
  generateName: kube-create-process
  labels:
    app: test
spec:
  serviceAccountName: airbyte-admin
  automountServiceAccountToken: true
  containers:
    - name: main
      image: airbyte/tests:dev-3
  restartPolicy: Never
