name: "Runner CI Python Tests"
description: "Runner CI Python Tests"
inputs:
  module-name:
    required: true
  module-folder:
    required: true

runs:
  using: "composite"
  steps:

    - name: Run tests of CI
      shell: bash
      run: |
          echo "make me, ${{ inputs.module-name }} in ${{ inputs.module-folder }}"

#