name: "Setup CI Tests Env"
description: "Setup CI Tests Env for all module types"
inputs:
  module-name:
    description: "Unique module name. e.g.: connectors/source-s3, connectors/destination-s3"
    required: true
  module-folder:
    description: "Path to module folder"
    required: true
  module-lang:
    description: "Detected module language. Available values: py, java"
    required: true
  sonar-host:
    required: true
  sonar-token:
    description: "Access token for using SonarQube API"
    required: true
  pull_request_id:
    description: "Unique PR ID. For example: airbyte/1234"
    default: "0"
  remove-sonar-project:
    description: "This flag should be used if needed to remove sonar project after using"
    default: false
runs:
  using: "composite"
  steps:

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Run Python Tests
      id: run-python-tests
      if: ${{ inputs.module-lang == 'py' }}
      uses: ./.github/actions/ci-py-tests
      with:
        module-name: ${{ inputs.module-name }}
        module-folder: ${{ inputs.module-folder }}

    - name: Run Java Tests
      id: run-java-tests
      if: ${{ inputs.module-lang == 'java' }}
      uses: ./.github/actions/ci-java-tests
      with:
        module-name: ${{ inputs.module-name }}
        module-folder: ${{ inputs.module-folder }}

    - name: Create SonarQube Project
      shell: bash
      id: create-sq-project
      run: |
        ci_sonar_qube --pull_request_name ${{ inputs.pull-request-id }} --create_module ${{ inputs.module-name }} --host ${{ inputs.sonar-host }} --token ${{ inputs.sonar-token }}
    - name: Remove SonarQube Project
      if: ${{ inputs.remove-sonar-project == true }}
      shell: bash
      id: remove-sq-project
      run: |
        ci_sonar_qube --pull_request_name ${{ inputs.pull-request-id }} --remove_module ${{ inputs.module-name }} --host ${{ inputs.sonar-host }} --token ${{ inputs.sonar-token }}
