name: Sonar Scan
on:
  push:
    branches:
      - h-chlor-patch-1 # test local branch
      - master # or the name of your main branch
jobs:
  sonar-scan:
    name: Sonar Scan
    runs-on: ubuntu-latest
    environment: more-secrets
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          projectBaseDir: airbyte-integrations/connectors
          args: >
	      -Dsonar.projectKey=airbytehq_airbyte
          -Dsonar.exclusions=**/*.java
          -Dsonar.tests=*/unit_tests/
          -Dsonar.verbose=true
        # If you wish to fail your job when the Quality Gate is red, uncomment the
        # following lines. This would typically be used to fail a deployment.
        # - uses: sonarsource/sonarqube-quality-gate-action@master
        #   timeout-minutes: 5
        #   env:
        #    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
