name: Using Codecov for Native Python Connections
on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    working-directory: airbyte-integrations/connectors
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests and collect coverage
        run: invoke test
      - name: Upload coverage to Codecov
        if: ${{ always() }}
        uses: codecov/codecov-action@v2
